#!/usr/bin/env bash
# =============================================================================
# promote.sh — Promote an application from one environment to another
#
# This script implements the GitOps promotion model:
#   dev → staging → prod
#
# It updates the targetRevision in the Application YAML, commits, and
# opens a PR.  A human reviews the PR; ArgoCD picks up the change on merge.
#
# Usage:
#   ./scripts/promote.sh --app monitoring --from dev --to staging --version v1.2.3
#
# Requirements:
#   - gh CLI installed and authenticated
#   - git configured with push access to the repo
# =============================================================================
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; CYAN='\033[0;36m'; NC='\033[0m'
log()  { echo -e "${CYAN}[INFO]${NC}  $*"; }
ok()   { echo -e "${GREEN}[OK]${NC}    $*"; }
err()  { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

# ------------------------------------------------------------------ #
# Argument parsing                                                   #
# ------------------------------------------------------------------ #
APP=""
FROM_ENV=""
TO_ENV=""
VERSION=""

while [[ $# -gt 0 ]]; do
  case $1 in
    --app)     APP="$2";      shift 2 ;;
    --from)    FROM_ENV="$2"; shift 2 ;;
    --to)      TO_ENV="$2";   shift 2 ;;
    --version) VERSION="$2";  shift 2 ;;
    -h|--help)
      echo "Usage: $0 --app <name> --from <env> --to <env> --version <tag>"
      exit 0 ;;
    *) err "Unknown argument: $1" ;;
  esac
done

[[ -z "$APP" || -z "$FROM_ENV" || -z "$TO_ENV" || -z "$VERSION" ]] && \
  err "All of --app, --from, --to, --version are required"

TARGET_FILE="applications/${TO_ENV}/${APP}.yaml"
[[ -f "$TARGET_FILE" ]] || err "Target file not found: $TARGET_FILE"

# ------------------------------------------------------------------ #
# Guard: only allow dev → staging → prod promotions                 #
# ------------------------------------------------------------------ #
ALLOWED_PROMOTIONS=("dev:staging" "staging:prod")
PROMOTION="${FROM_ENV}:${TO_ENV}"
VALID=false
for p in "${ALLOWED_PROMOTIONS[@]}"; do
  [[ "$p" == "$PROMOTION" ]] && VALID=true && break
done
[[ "$VALID" == "false" ]] && err "Invalid promotion path: ${FROM_ENV} → ${TO_ENV}. Allowed: dev→staging, staging→prod"

# ------------------------------------------------------------------ #
# Production safety gate                                            #
# ------------------------------------------------------------------ #
if [[ "$TO_ENV" == "prod" ]]; then
  echo -e "\n${RED}WARNING: You are promoting to PRODUCTION.${NC}"
  read -r -p "Confirm promote ${APP} ${VERSION} to prod? (yes/no): " CONFIRM
  [[ "$CONFIRM" == "yes" ]] || err "Aborted."
fi

# ------------------------------------------------------------------ #
# Create branch, update targetRevision, open PR                     #
# ------------------------------------------------------------------ #
BRANCH="promote/${APP}-${VERSION}-to-${TO_ENV}"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

log "Creating branch: ${BRANCH}"
git checkout -b "$BRANCH"

log "Updating targetRevision in ${TARGET_FILE} to ${VERSION}..."
# Replace only the targetRevision line (assumes one per file)
sed -i "s|targetRevision:.*|targetRevision: ${VERSION}|" "$TARGET_FILE"

git add "$TARGET_FILE"
git commit -m "chore(promote): ${APP} ${VERSION} → ${TO_ENV} [${TIMESTAMP}]

Promoted from: ${FROM_ENV}
Promoted to:   ${TO_ENV}
Application:   ${APP}
Version:       ${VERSION}
"

log "Pushing branch..."
git push --set-upstream origin "$BRANCH"

log "Opening Pull Request..."
gh pr create \
  --title "promote(${TO_ENV}): ${APP} → ${VERSION}" \
  --body "## Promotion: \`${APP}\` to \`${TO_ENV}\`

| Field       | Value          |
|-------------|----------------|
| Application | \`${APP}\`     |
| From        | \`${FROM_ENV}\`|
| To          | \`${TO_ENV}\`  |
| Version     | \`${VERSION}\` |
| Timestamp   | \`${TIMESTAMP}\` |

### Checklist
- [ ] Verified application is healthy in \`${FROM_ENV}\`
- [ ] Reviewed diff in this PR
- [ ] Smoke test plan documented
- [ ] On-call engineer notified (prod only)

_This PR was generated by \`scripts/promote.sh\`._" \
  --base main \
  --head "$BRANCH"

ok "PR created. After review and merge, ArgoCD will detect the change."
